// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CLAW_H
#define CLAW_H
#include "frc/commands/Subsystem.h"
#include "frc/WPILib.h"
#include "rev/CanSparkMax.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Claw: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	
	std::shared_ptr<rev::CANSparkMax> sparkyClaw;
	//std::shared_ptr<frc::Encoder> encody;

    
	std::shared_ptr<rev::CANEncoder> encody;
	int P, I, D, error, setpoint, rcw;
	double integral, derivative, previous_error;
public:
	Claw();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
void OpenClaw();
void CloseClaw();
void Stop();
void setSetPoint(int setpoint);
void PID();
};

#endif
