// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "frc/WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	std::shared_ptr<frc::Joystick> joystick2;
	std::shared_ptr<frc::JoystickButton> lBumper6;
	std::shared_ptr<frc::JoystickButton> rBumper5;
	std::shared_ptr<frc::JoystickButton> y4;
	std::shared_ptr<frc::JoystickButton> b2;
	std::shared_ptr<frc::JoystickButton> a1;
	std::shared_ptr<frc::Joystick> joystick1;
	std::shared_ptr<frc::JoystickButton> rB6;
	std::shared_ptr<frc::JoystickButton> lB5;
	std::shared_ptr<frc::JoystickButton> ltrig11;
	std::shared_ptr<frc::JoystickButton> rtrig12;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> getJoystick1();
	std::shared_ptr<frc::Joystick> getJoystick2();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
